### 로그인
POST http://localhost:1208/auth/login
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "employeeId": "ap_second",
  "employeePassword": "ap_second"
}

### 결재 대기 문서 조회
GET http://localhost:1208/approval/2
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3Mzc2NTM4NTg1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLsl7Dsnbjsp4AiLCJzdWIiOiJpbmppIiwiZW1wQ29kZSI6MTYsImVtcGxveWVlRW1haWwiOiJpbmppQGdtYWlsLmNvbSIsImV4cCI6MTcwNzM4MDEzOCwiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZU5vIjowLCJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfQURNSU4iLCJhdXRob3JpdHlEZXNjIjoi6rSA66as7J6QIn19XX0.TMTPCXDvs-pWe72Dc7zH7gpsZmZ66wRuuwJje5X-Uy0

### 결재 문서 상신 - 휴가신청서
POST http://localhost:1208/approval/submit-on-leave
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4NDUwMDI4MDI0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLquYDrr7zsnqwiLCJzdWIiOiJhcF9zZWNvbmQiLCJlbXBDb2RlIjozMSwiZW1wbG95ZWVFbWFpbCI6ImFwX3NlY29uZEBnbWFpbC5jb20iLCJlbXBsb3llZUlkIjoiYXBfc2Vjb25kIiwiZXhwIjoxNzA4NDUzNjI4LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MzEsImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9VU0VSIn19XX0.lwLkG5wiR4icb9L26_EOpmGxG_5FFT0w5iVLDBT1W6I

### 결재 문서 상신 - 연장근로신청서
POST http://localhost:1208/approval/submit-overwork
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4NTA2OTE3NTM4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLquYDrr7zsnqwiLCJzdWIiOiJhcF9zZWNvbmQiLCJlbXBEZXB0TmFtZSI6Iuy0neustO2MgCIsImVtcENvZGUiOjMxLCJlbXBsb3llZUVtYWlsIjoiYXBfc2Vjb25kQGdtYWlsLmNvbSIsImVtcEdyb3VwQ29kZSI6MSwiZW1wbG95ZWVJZCI6ImFwX3NlY29uZCIsImV4cCI6MTcwODUxMDUxNywiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZUNvZGUiOjMxLCJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MSwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfVVNFUiJ9fV19.71HJ7_80rhmvPW_xUPUat-hhSbKINBxl2HovT1rN9uo

### 결재 문서 상신 - SW사용신청서
POST http://localhost:1208/approval/submit-sw-use
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4NDUwMDI4MDI0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLquYDrr7zsnqwiLCJzdWIiOiJhcF9zZWNvbmQiLCJlbXBDb2RlIjozMSwiZW1wbG95ZWVFbWFpbCI6ImFwX3NlY29uZEBnbWFpbC5jb20iLCJlbXBsb3llZUlkIjoiYXBfc2Vjb25kIiwiZXhwIjoxNzA4NDUzNjI4LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MzEsImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9VU0VSIn19XX0.lwLkG5wiR4icb9L26_EOpmGxG_5FFT0w5iVLDBT1W6I

### 결재 문서 상신 - 근무형태신청서
POST http://localhost:1208/approval/submit-work-type
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4NDUwMDI4MDI0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLquYDrr7zsnqwiLCJzdWIiOiJhcF9zZWNvbmQiLCJlbXBDb2RlIjozMSwiZW1wbG95ZWVFbWFpbCI6ImFwX3NlY29uZEBnbWFpbC5jb20iLCJlbXBsb3llZUlkIjoiYXBfc2Vjb25kIiwiZXhwIjoxNzA4NDUzNjI4LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MzEsImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9VU0VSIn19XX0.lwLkG5wiR4icb9L26_EOpmGxG_5FFT0w5iVLDBT1W6I

### 상신 문서 조회
GET http://localhost:1208/approval/outbox-approval
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4NDUwMDI4MDI0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLquYDrr7zsnqwiLCJzdWIiOiJhcF9zZWNvbmQiLCJlbXBDb2RlIjozMSwiZW1wbG95ZWVFbWFpbCI6ImFwX3NlY29uZEBnbWFpbC5jb20iLCJlbXBsb3llZUlkIjoiYXBfc2Vjb25kIiwiZXhwIjoxNzA4NDUzNjI4LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MzEsImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9VU0VSIn19XX0.lwLkG5wiR4icb9L26_EOpmGxG_5FFT0w5iVLDBT1W6I

### 결재 대기 문서 조회
GET http://localhost:1208/approval/inbox-approval
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3NTY4MDI4NzE0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsrDsnqzsnpAxIiwic3ViIjoiYXBfc2Vjb25kIiwiZW1wQ29kZSI6MzEsImVtcGxveWVlRW1haWwiOiJhcF9zZWNvbmRAZ21haWwuY29tIiwiZXhwIjoxNzA3NTcxNjI4LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.LferBf7f8moKHewxPOefVhyHLvKatULaiOSH4FIM2N4

### 결재하기
PUT http://localhost:1208/approval/approvement/40
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3ODE3MjI1NzE5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsrDsnqzsnpAyIiwic3ViIjoiYXBfdGhpcmQiLCJlbXBDb2RlIjozMiwiZW1wbG95ZWVFbWFpbCI6ImFwX3RoaXJkQGdtYWlsLmNvbSIsImV4cCI6MTcwNzgyMDgyNSwiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZU5vIjowLCJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfQURNSU4iLCJhdXRob3JpdHlEZXNjIjoi6rSA66as7J6QIn19XX0.AgUkwKekN8pdTtHtdG7xiEJMC-SQlbXvjDYpsHcVb80

### 반려하기
PUT http://localhost:1208/approval/rejection/36
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3NTY4MDI4NzE0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsrDsnqzsnpAxIiwic3ViIjoiYXBfc2Vjb25kIiwiZW1wQ29kZSI6MzEsImVtcGxveWVlRW1haWwiOiJhcF9zZWNvbmRAZ21haWwuY29tIiwiZXhwIjoxNzA3NTcxNjI4LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.LferBf7f8moKHewxPOefVhyHLvKatULaiOSH4FIM2N4

### 회수하기
PUT http://localhost:1208/approval/retrieval/34
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3NTcwNDkwMTUxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLquLDslYjsnpAiLCJzdWIiOiJhcF9maXJzdCIsImVtcENvZGUiOjMwLCJlbXBsb3llZUVtYWlsIjoiYXBfZmlyc3RAZ21haWwuY29tIiwiZXhwIjoxNzA3NTc0MDkwLCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.TTcPJbkW4qEdjLaWfVtrxQlTmfSRr4Oj4KNXJmCFb3I

### 결재 진행 중인 문서 조회
GET http://localhost:1208/approval/outbox-on-process
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4NDEzNTc3MTk1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshpDtnaXrr7wiLCJzdWIiOiJhcF9maXJzdCIsImVtcENvZGUiOjMwLCJlbXBsb3llZUVtYWlsIjoiYXBfZmlyc3RAZ21haWwuY29tIiwiZW1wbG95ZWVJZCI6ImFwX2ZpcnN0IiwiZXhwIjoxNzA4NDE3MTc3LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MzAsImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9VU0VSIn19XX0.aiYE6aNG_P_B_cIQuJQiEbgn63cDRoBnjxHrDne-1lU

### 결재 완료 문서 조회
GET http://localhost:1208/approval/outbox-finished
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3NTc3NzQ3OTk4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLquLDslYjsnpAiLCJzdWIiOiJhcF9maXJzdCIsImVtcENvZGUiOjMwLCJlbXBsb3llZUVtYWlsIjoiYXBfZmlyc3RAZ21haWwuY29tIiwiZXhwIjoxNzA3NTgxMzQ3LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.EKjMAUvm0mzaZSjgsKxifbMT2AymUeHmY_wSyEVfgHQ

### 반려 문서 조회
GET http://localhost:1208/approval/outbox-rejected
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3NTc3NzQ3OTk4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLquLDslYjsnpAiLCJzdWIiOiJhcF9maXJzdCIsImVtcENvZGUiOjMwLCJlbXBsb3llZUVtYWlsIjoiYXBfZmlyc3RAZ21haWwuY29tIiwiZXhwIjoxNzA3NTgxMzQ3LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.EKjMAUvm0mzaZSjgsKxifbMT2AymUeHmY_wSyEVfgHQ

### 회수 문서 조회
GET http://localhost:1208/approval/outbox-retrieved
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3NTc3NzQ3OTk4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLquLDslYjsnpAiLCJzdWIiOiJhcF9maXJzdCIsImVtcENvZGUiOjMwLCJlbXBsb3llZUVtYWlsIjoiYXBfZmlyc3RAZ21haWwuY29tIiwiZXhwIjoxNzA3NTgxMzQ3LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.EKjMAUvm0mzaZSjgsKxifbMT2AymUeHmY_wSyEVfgHQ

### 임시 저장
POST http://localhost:1208/approval/save-approval
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3NTc3NzQ3OTk4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLquLDslYjsnpAiLCJzdWIiOiJhcF9maXJzdCIsImVtcENvZGUiOjMwLCJlbXBsb3llZUVtYWlsIjoiYXBfZmlyc3RAZ21haWwuY29tIiwiZXhwIjoxNzA3NTgxMzQ3LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.EKjMAUvm0mzaZSjgsKxifbMT2AymUeHmY_wSyEVfgHQ

### 임시 저장 문서 리스트 조회
GET http://localhost:1208/approval/outbox-saved
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3NTc3NzQ3OTk4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLquLDslYjsnpAiLCJzdWIiOiJhcF9maXJzdCIsImVtcENvZGUiOjMwLCJlbXBsb3llZUVtYWlsIjoiYXBfZmlyc3RAZ21haWwuY29tIiwiZXhwIjoxNzA3NTgxMzQ3LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.EKjMAUvm0mzaZSjgsKxifbMT2AymUeHmY_wSyEVfgHQ

### 수신함 - 결재 완료함
GET http://localhost:1208/approval/inbox-finished
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3Nzk3MDc0OTI4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsrDsnqzsnpAxIiwic3ViIjoiYXBfc2Vjb25kIiwiZW1wQ29kZSI6MzEsImVtcGxveWVlRW1haWwiOiJhcF9zZWNvbmRAZ21haWwuY29tIiwiZXhwIjoxNzA3ODAwNjc0LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.aCsuuGpc0bN4eGZD215T4y5lrFdgxD45-KC86Tzoa9k

### 대리 결재 지정
POST http://localhost:1208/approval/set-represent
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3ODE2OTUzNDA5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsrDsnqzsnpAxIiwic3ViIjoiYXBfc2Vjb25kIiwiZW1wQ29kZSI6MzEsImVtcGxveWVlRW1haWwiOiJhcF9zZWNvbmRAZ21haWwuY29tIiwiZXhwIjoxNzA3ODIwNTUzLCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.jK2b-T5hp8hCSmKeZom0lFe_J9lrtcfo0uXbgZMg1Bo