### 결재 문서 조회
GET http://localhost:1208/approval/2
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3MjEyMzc1ODMxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLsl7Dsnbjsp4AiLCJzdWIiOiJpbmppIiwiZW1wQ29kZSI6MTYsImVtcGxveWVlRW1haWwiOiJpbmppQGdtYWlsLmNvbSIsImV4cCI6MTcwNzIxNTk3NSwiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZU5vIjowLCJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfQURNSU4iLCJhdXRob3JpdHlEZXNjIjoi6rSA66as7J6QIn19XX0.PERd9zyPgk5NnpG5_hVLsVikbnRwieXZIPPsFVv5PAs

### 결재 문서 상신
POST http://localhost:1208/approval/submit-approval
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3MjEyMzc1ODMxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLsl7Dsnbjsp4AiLCJzdWIiOiJpbmppIiwiZW1wQ29kZSI6MTYsImVtcGxveWVlRW1haWwiOiJpbmppQGdtYWlsLmNvbSIsImV4cCI6MTcwNzIxNTk3NSwiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZU5vIjowLCJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfQURNSU4iLCJhdXRob3JpdHlEZXNjIjoi6rSA66as7J6QIn19XX0.PERd9zyPgk5NnpG5_hVLsVikbnRwieXZIPPsFVv5PAs

{
  "approvalForm": "재택근무신청서",
  "whetherSavingApproval": "N"
}