
### 내 출퇴근 내역(목록)
GET http://localhost:1208/api/v1/attendances/lists?yearMonth=2024-02&offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA5MTI2MjMxOTc4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJkZXBhcnRtZW50TmFtZSI6IklU7Jq07JiB7YyAIiwiZW1wbG95ZWVOYW1lIjoi7ISc67O07ZicIiwic3ViIjoidXNlcjA5IiwiZW1wQ29kZSI6MTQsImRlcGFydG1lbnRDb2RlIjo4LCJlbXBsb3llZUVtYWlsIjoia29vb3BwNTVAZ21haWwuY29tIiwiZW1wR3JvdXBDb2RlIjozLCJlbXBsb3llZUlkIjoidXNlcjA5IiwiZXhwIjoxNzA5MTYyMjMxLCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MTQsImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9VU0VSIn19XX0.7qMxBH4M-qoE8Hijhe3VjwW9Nu9a6kAvwzZ6UqxEWlI




### 내가 신청한 문서-기안
GET http://localhost:1208/api/v1/attendances/my/documents-waiting?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA4NzQ3MjkwNjA4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshpDtnaXrr7wiLCJzdWIiOiJhcF9maXJzdCIsImVtcERlcHROYW1lIjoi7LSd66y07YyAIiwiZW1wQ29kZSI6MzAsImVtcGxveWVlRW1haWwiOiJhcF9maXJzdEBnbWFpbC5jb20iLCJlbXBHcm91cENvZGUiOjEsImVtcGxveWVlSWQiOiJhcF9maXJzdCIsImV4cCI6MTcwODc1MDg5MCwiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZUNvZGUiOjMwLCJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MSwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfVVNFUiJ9fV19.G4DEuVD9uMFKXm8hJOfy2hDM6tjJz3XtkFhOwqrlmCI




### 내가 신청한 문서-승인
GET http://localhost:1208/api/v1/attendances/my/documents-payment?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA4NDg4MTk4NzI0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXrgqgiLCJzdWIiOiJ1c2VyNzc3IiwiZW1wQ29kZSI6MzQsImVtcGxveWVlRW1haWwiOiJrYW5nNzc3QGdtYWlsLmNvbSIsImVtcGxveWVlSWQiOiJ1c2VyNzc3IiwiZXhwIjoxNzA4NDkxNzk4LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MzQsImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9VU0VSIn19XX0.4aZa-V5fFAwvFwIMqcbW1X7yHYXYD3dBjaj2iEmJdjU



### 내가 신청한 문서-반려
GET http://localhost:1208/api/v1/attendances/my/documents-companion?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA4OTM0MTM1ODk3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshpDtnaXrr7wiLCJzdWIiOiJhcF9maXJzdCIsImVtcERlcHROYW1lIjoi7LSd66y07YyAIiwiZW1wQ29kZSI6MzAsImVtcGxveWVlRW1haWwiOiJhcF9maXJzdEBnbWFpbC5jb20iLCJlbXBHcm91cENvZGUiOjEsImVtcGxveWVlSWQiOiJhcF9maXJzdCIsImV4cCI6MTcwODkzNzczNSwiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZUNvZGUiOjMwLCJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MSwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfVVNFUiJ9fV19.izVZv8lzFqDflVKbX1fLNhxk_jHnJ__MMW0l2C-1A2c



### 내가 결재한 문서-승인
GET http://localhost:1208/api/v1/attendances/payment/completed?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA4NDg4MTk4NzI0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXrgqgiLCJzdWIiOiJ1c2VyNzc3IiwiZW1wQ29kZSI6MzQsImVtcGxveWVlRW1haWwiOiJrYW5nNzc3QGdtYWlsLmNvbSIsImVtcGxveWVlSWQiOiJ1c2VyNzc3IiwiZXhwIjoxNzA4NDkxNzk4LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MzQsImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9VU0VSIn19XX0.4aZa-V5fFAwvFwIMqcbW1X7yHYXYD3dBjaj2iEmJdjU




### 내가 결재한 문서-반려
GET http://localhost:1208/api/v1/attendances/payment/rejection?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA4NDk3Njg5NTU2LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXrgqgiLCJzdWIiOiJ1c2VyNzc3IiwiZW1wQ29kZSI6MzQsImVtcGxveWVlRW1haWwiOiJrYW5nNzc3QGdtYWlsLmNvbSIsImVtcGxveWVlSWQiOiJ1c2VyNzc3IiwiZXhwIjoxNzA4NTAxMjg5LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MzQsImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9VU0VSIn19XX0.9pOw4-fKETLS7P4OBRDJJNvYOP5k7OnUGkdi27cvcZQ



### 내가 결재할 문서-대기
GET http://localhost:1208/api/v1/attendances/payment/waiting?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA4NDg4MTk4NzI0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXrgqgiLCJzdWIiOiJ1c2VyNzc3IiwiZW1wQ29kZSI6MzQsImVtcGxveWVlRW1haWwiOiJrYW5nNzc3QGdtYWlsLmNvbSIsImVtcGxveWVlSWQiOiJ1c2VyNzc3IiwiZXhwIjoxNzA4NDkxNzk4LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MzQsImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9VU0VSIn19XX0.4aZa-V5fFAwvFwIMqcbW1X7yHYXYD3dBjaj2iEmJdjU




### 근태관리 메인 화면 출퇴근 화면
GET http://localhost:1208/api/v1/attendances/main
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA5MTI2MjMxOTc4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJkZXBhcnRtZW50TmFtZSI6IklU7Jq07JiB7YyAIiwiZW1wbG95ZWVOYW1lIjoi7ISc67O07ZicIiwic3ViIjoidXNlcjA5IiwiZW1wQ29kZSI6MTQsImRlcGFydG1lbnRDb2RlIjo4LCJlbXBsb3llZUVtYWlsIjoia29vb3BwNTVAZ21haWwuY29tIiwiZW1wR3JvdXBDb2RlIjozLCJlbXBsb3llZUlkIjoidXNlcjA5IiwiZXhwIjoxNzA5MTYyMjMxLCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MTQsImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9VU0VSIn19XX0.7qMxBH4M-qoE8Hijhe3VjwW9Nu9a6kAvwzZ6UqxEWlI






### 근태관리 메인 화면 출근 인서트
POST http://localhost:1208/api/v1/attendances/main
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA4MzkwNzc5NDI3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImthbmdoYWVyaW5AZ21haWwuY29tIiwiZW1wbG95ZWVJZCI6InVzZXIwNyIsImV4cCI6MTcwODM5NDM3OSwiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZUNvZGUiOjEyLCJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfQURNSU4ifX1dfQ.j9tBA17IgM3ZnGmNAwhxwI_qcRzBsmo8N5XmxYvwBpM

{
  "attendanceManagementArrivalTime": "2024-02-07T08:57:02",
  "attendanceManagementDepartureTime": "2024-02-07T00:00:00",
  "attendanceManagementState" : "정상",
  "attendanceManagementWorkDay" : "2024-02-05"
}




###  관리자 근태 화면 연차할당 완료
GET http://localhost:1208/api/v1/attendances/admin/vacation?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA4NTkwNjM1NTI2LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshJzrs7TtmJwiLCJzdWIiOiJ1c2VyMDkiLCJlbXBEZXB0TmFtZSI6IklU7Jq07JiB7YyAIiwiZW1wQ29kZSI6MTQsImVtcGxveWVlRW1haWwiOiJra2tycnI1NUBnbWFpbC5jb20iLCJlbXBHcm91cENvZGUiOjMsImVtcGxveWVlSWQiOiJ1c2VyMDkiLCJleHAiOjE3MDg1OTQyMzUsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVDb2RlIjoxNCwiYXV0aG9yaXR5Q29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eU5hbWUiOiJST0xFX1VTRVIifX1dfQ.Ntd2h3-Kr7ongvaaznAl_4F57-cqKr3EjrBh1o9CcT0


###  관리자 근태 화면 연차미할당
GET http://localhost:1208/api/v1/attendances/admin/no/vacation?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA4NTkwNjM1NTI2LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshJzrs7TtmJwiLCJzdWIiOiJ1c2VyMDkiLCJlbXBEZXB0TmFtZSI6IklU7Jq07JiB7YyAIiwiZW1wQ29kZSI6MTQsImVtcGxveWVlRW1haWwiOiJra2tycnI1NUBnbWFpbC5jb20iLCJlbXBHcm91cENvZGUiOjMsImVtcGxveWVlSWQiOiJ1c2VyMDkiLCJleHAiOjE3MDg1OTQyMzUsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVDb2RlIjoxNCwiYXV0aG9yaXR5Q29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eU5hbWUiOiJST0xFX1VTRVIifX1dfQ.Ntd2h3-Kr7ongvaaznAl_4F57-cqKr3EjrBh1o9CcT0


### 연차 인서트
POST http://localhost:1208/api/v1/attendances/admin/vacation
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA4NTk1MDMwODI4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshJzrs7TtmJwiLCJzdWIiOiJ1c2VyMDkiLCJlbXBEZXB0TmFtZSI6IklU7Jq07JiB7YyAIiwiZW1wQ29kZSI6MTQsImVtcGxveWVlRW1haWwiOiJra2tycnI1NUBnbWFpbC5jb20iLCJlbXBHcm91cENvZGUiOjMsImVtcGxveWVlSWQiOiJ1c2VyMDkiLCJleHAiOjE3MDg1OTg2MzAsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVDb2RlIjoxNCwiYXV0aG9yaXR5Q29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eU5hbWUiOiJST0xFX1VTRVIifX1dfQ.4ep2wslIvtXj4WAizwox0yjo1kjPUuFCOyiZtqEJPNc



### 근태관리 메인 화면 퇴근 업데이트
PUT http://localhost:1208/api/v1/attendances/main
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA3MjY5OTkwNDg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshJzrs7TtmJwiLCJzdWIiOiJ1c2VyMDkiLCJlbXBDb2RlIjoxNCwiZW1wbG95ZWVFbWFpbCI6Imtra3JycjU1QGdtYWlsLmNvbSIsImV4cCI6MTcwNzI3MzU5MCwiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZU5vIjowLCJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfQURNSU4iLCJhdXRob3JpdHlEZXNjIjoi6rSA66as7J6QIn19XX0.-dKi1ffqCgAqXy8QW15Y4j2-oUB7JXTKHxXGUe_-fLw


{
  "attendanceManagementDepartureTime" : "2024-02-07T17:01:02",
  "attendanceManagementState" : "정상"
}


#### 문서 상세보기
GET http://localhost:1208/api/v1/attendances/document/69/14
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA5MDA1MTgzMDc1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshJzrs7TtmJwiLCJzdWIiOiJ1c2VyMDkiLCJlbXBEZXB0TmFtZSI6IklU7Jq07JiB7YyAIiwiZW1wQ29kZSI6MTQsImVtcGxveWVlRW1haWwiOiJra2tycnI1NUBnbWFpbC5jb20iLCJlbXBHcm91cENvZGUiOjMsImVtcGxveWVlSWQiOiJ1c2VyMDkiLCJleHAiOjE3MDkwMDg3ODMsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVDb2RlIjoxNCwiYXV0aG9yaXR5Q29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eU5hbWUiOiJST0xFX1VTRVIifX1dfQ.yC4Rv75ASCNVZkJGoOXAzz7v55JKT4od7m-VpIKkNqI


### 문서 상세보기 결재 하기
PUT http://localhost:1208/api/v1/attendances/document/70/14
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA5MDExMDcyNzAyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshJzrs7TtmJwiLCJzdWIiOiJ1c2VyMDkiLCJlbXBEZXB0TmFtZSI6IklU7Jq07JiB7YyAIiwiZW1wQ29kZSI6MTQsImVtcGxveWVlRW1haWwiOiJra2tycnI1NUBnbWFpbC5jb20iLCJlbXBHcm91cENvZGUiOjMsImVtcGxveWVlSWQiOiJ1c2VyMDkiLCJleHAiOjE3MDkwMTQ2NzIsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVDb2RlIjoxNCwiYXV0aG9yaXR5Q29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eU5hbWUiOiJST0xFX1VTRVIifX1dfQ.mSVd1Kea--2dgh-PFMJRb0Npi9jaN8U01pf6FD-Q44A





