
### 내 출퇴근 내역(목록)
GET http://localhost:1208/api/v1/attendances/lists?yearMonth=2024-02&offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA3Nzg2MTk5NTE3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshJzrs7TtmJwiLCJzdWIiOiJ1c2VyMDkiLCJlbXBDb2RlIjoxNCwiZW1wbG95ZWVFbWFpbCI6Imtra3JycjU1QGdtYWlsLmNvbSIsImV4cCI6MTcwNzc4OTc5OSwiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZU5vIjowLCJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfQURNSU4iLCJhdXRob3JpdHlEZXNjIjoi6rSA66as7J6QIn19XX0.FF4HKaJA6AydollWpOvrLyWYtUdd7pN1QGpo5kGfPe0



### 내가 신청한 문서-기안
GET http://localhost:1208/api/v1/attendances/my/documents-waiting?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA3NjIwODg5NjU4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJleHAiOjE3MDc2MjQ0ODksImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19.-KFHjykOm46aF2sKDu2y449FKAGaFwQlkcj-Pj-hYRk



### 내가 신청한 문서-승인
GET http://localhost:1208/api/v1/attendances/my/documents-payment?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA3NjIwODg5NjU4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJleHAiOjE3MDc2MjQ0ODksImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19.-KFHjykOm46aF2sKDu2y449FKAGaFwQlkcj-Pj-hYRk


### 내가 신청한 문서-반려
GET http://localhost:1208/api/v1/attendances/my/documents-companion?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA3NjIwODg5NjU4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJleHAiOjE3MDc2MjQ0ODksImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19.-KFHjykOm46aF2sKDu2y449FKAGaFwQlkcj-Pj-hYRk




### 내가 결재한 문서-승인
GET http://localhost:1208/api/v1/attendances/payment/completed?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA3ODA2NzUzNTY4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshJzrs7TtmJwiLCJzdWIiOiJ1c2VyMDkiLCJlbXBDb2RlIjoxNCwiZW1wbG95ZWVFbWFpbCI6Imtra3JycjU1QGdtYWlsLmNvbSIsImV4cCI6MTcwNzgxMDM1MywiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZU5vIjowLCJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfQURNSU4iLCJhdXRob3JpdHlEZXNjIjoi6rSA66as7J6QIn19XX0.dDxIeaDeWWDKMeif2oIRhrnxRrwGU80GComKBseJhF4


### 내가 결재한 문서-반려
GET http://localhost:1208/api/v1/attendances/payment/rejection?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA3ODAxOTIzNTYzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshJzrs7TtmJwiLCJzdWIiOiJ1c2VyMDkiLCJlbXBDb2RlIjoxNCwiZW1wbG95ZWVFbWFpbCI6Imtra3JycjU1QGdtYWlsLmNvbSIsImV4cCI6MTcwNzgwNTUyMywiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZU5vIjowLCJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfQURNSU4iLCJhdXRob3JpdHlEZXNjIjoi6rSA66as7J6QIn19XX0.74ttVZVAGa7P0lYnxXd7w4mIr6QqcXnb3BR9l4qg0jI



### 내가 결재할 문서-대기
GET http://localhost:1208/api/v1/attendances/payment/waiting?offset=1
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA3ODA2NzUzNTY4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshJzrs7TtmJwiLCJzdWIiOiJ1c2VyMDkiLCJlbXBDb2RlIjoxNCwiZW1wbG95ZWVFbWFpbCI6Imtra3JycjU1QGdtYWlsLmNvbSIsImV4cCI6MTcwNzgxMDM1MywiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZU5vIjowLCJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfQURNSU4iLCJhdXRob3JpdHlEZXNjIjoi6rSA66as7J6QIn19XX0.dDxIeaDeWWDKMeif2oIRhrnxRrwGU80GComKBseJhF4



### 근태관리 메인 화면 출퇴근 화면
GET http://localhost:1208/api/v1/attendances/main
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA3ODE1NzM2NDY1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshJzrs7TtmJwiLCJzdWIiOiJ1c2VyMDkiLCJlbXBDb2RlIjoxNCwiZW1wbG95ZWVFbWFpbCI6Imtra3JycjU1QGdtYWlsLmNvbSIsImV4cCI6MTcwNzgxOTMzNiwiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZU5vIjowLCJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfQURNSU4iLCJhdXRob3JpdHlEZXNjIjoi6rSA66as7J6QIn19XX0.HrdxPWaYpH6VNE4P6_HJNh9cr2mEtoVGHNwmLgyk_NM



### 근태관리 메인 화면 출근 인서트
POST http://localhost:1208/api/v1/attendances/main
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA3MjY5OTkwNDg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshJzrs7TtmJwiLCJzdWIiOiJ1c2VyMDkiLCJlbXBDb2RlIjoxNCwiZW1wbG95ZWVFbWFpbCI6Imtra3JycjU1QGdtYWlsLmNvbSIsImV4cCI6MTcwNzI3MzU5MCwiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZU5vIjowLCJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfQURNSU4iLCJhdXRob3JpdHlEZXNjIjoi6rSA66as7J6QIn19XX0.-dKi1ffqCgAqXy8QW15Y4j2-oUB7JXTKHxXGUe_-fLw

{
  "attendanceManagementArrivalTime": "2024-02-07T08:57:02",
  "attendanceManagementDepartureTime": "2024-02-07T00:00:00",
  "attendanceManagementState" : "정상",
  "attendanceManagementWorkDay" : "2024-02-05"
}


### 근태관리 메인 화면 퇴근 업데이트
PUT http://localhost:1208/api/v1/attendances/main
Content-Type: application/json
Accept: */*
Authorization:Bear eyJkYXRlIjoxNzA3MjY5OTkwNDg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLshJzrs7TtmJwiLCJzdWIiOiJ1c2VyMDkiLCJlbXBDb2RlIjoxNCwiZW1wbG95ZWVFbWFpbCI6Imtra3JycjU1QGdtYWlsLmNvbSIsImV4cCI6MTcwNzI3MzU5MCwiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZU5vIjowLCJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfQURNSU4iLCJhdXRob3JpdHlEZXNjIjoi6rSA66as7J6QIn19XX0.-dKi1ffqCgAqXy8QW15Y4j2-oUB7JXTKHxXGUe_-fLw


{
  "attendanceManagementDepartureTime" : "2024-02-07T17:01:02",
  "attendanceManagementState" : "정상"
}
