### 근태관리 메인 화면 출퇴근


### 내 출퇴근 내역(목록)
GET http://localhost:1208/api/v1/attendances/list

### 내가 신청한 문서-대기


### 내가 신청한 문서-승인


### 내가 신청한 문서-반려


### 내가 결재할 문서-대기


### 내가 결재한 문서-승인


### 내가 결재한 문서-반려
