### 조직도 전체 사원 조회
GET http://localhost:1208/api/v1/group/chartlist?offset=1
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA2OTI1ODA5NTQzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBsb3llZUVtYWlsIjoia2trcnJyMTJAZ21haWwuY29tIiwiZXhwIjoxNzA2OTI5NDA5LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.Mkh52ToYLqScDBHNkQ5RBH9BvXd8CCRLHhUxkViJpnk

### 부서명이랑 사원이름으로 조회하기
GET http://localhost:1208/api/v1/group/chartlist/search?s=개발팀
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA2OTI1ODA5NTQzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBsb3llZUVtYWlsIjoia2trcnJyMTJAZ21haWwuY29tIiwiZXhwIjoxNzA2OTI5NDA5LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.Mkh52ToYLqScDBHNkQ5RBH9BvXd8CCRLHhUxkViJpnk
