### 조직도 전체 사원 조회
GET http://localhost:1208/api/v1/group/chartlist?offset=1
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3MjA3MjAxOTMxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJleHAiOjE3MDcyMTA4MDEsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19._7yy0cVYJPGLwTl_TpXfE4QIAmFbI7QDXBy1d17-FWw

### 부서명이랑 사원이름으로 조회하기
GET http://localhost:1208/api/v1/group/chartlist/search?s=개발팀
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA2OTMyNDI0MDIxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBsb3llZUVtYWlsIjoia2FuZ2hhZXJpbkBnbWFpbC5jb20iLCJleHAiOjE3MDY5MzYwMjQsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19.QyxQELhfPZ3XXPdoLakOIoPy0-YDWHUAxYTcS1HXlFU
