### 회원가입
POST http://localhost:1208/auth/signup
Content-Type: application/json
Accept: */*

{
  "employeeId": "user07",
  "employeePassword": "pass07",
  "employeeName": "강해린",
  "employeeEmail": "kkkrrr12@gmail.com",
  "employeeRetirementDate": "",
  "employeeBirthDate": "2003-03-03",
  "empAddress": "동대문구 종로구 하이미디어",
  "empPhone": "010-3444-4132"

}

### 로그인
POST http://localhost:1208/auth/login
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "employeeId": "user07",
  "employeePassword": "pass34"
}

