### 회원가입
POST http://localhost:1208/auth/signup
Content-Type: application/json
Accept: */*

{
  "employeeId": "inji",
  "employeePassword": "0202",
  "employeeName": "연인지",
  "employeeEmail": "inji@gmail.com",
  "employeeRetirementDate": "",
  "employeeBirthDate": "1993-12-08",
  "empAddress": "서울시 서초구 강남대로305",
  "empPhone": "010-1111-2222"

}

### 로그인
POST http://localhost:1208/auth/login
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "employeeId": "inji",
  "employeePassword": "0202"
}

