### 메인페이지 정보 조회

### 메인페이지 최근순서대로 게시판 리스트 조회 <게시글 번호, 게시글 제목, 게시글 내용, 날짜, 조회수>
GET http://localhost:1208/api/v1/mainpage/boardlist
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3MjA3MjAxOTMxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJleHAiOjE3MDcyMTA4MDEsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19._7yy0cVYJPGLwTl_TpXfE4QIAmFbI7QDXBy1d17-FWw


###메인페이지 프로젝트 리스트 조회
GET http://localhost:1208/api/v1/mainpage/projectlist
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3MjA3MjAxOTMxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJleHAiOjE3MDcyMTA4MDEsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19._7yy0cVYJPGLwTl_TpXfE4QIAmFbI7QDXBy1d17-FWw



###메인페이지 근태 출퇴근 인서트
POST http://localhost:1208/api/v1/mainpage/arrive
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA5MDgyODYyMDg0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJkZXBhcnRtZW50TmFtZSI6Iu2ajOqzhO2MgCIsImVtcGxveWVlTmFtZSI6IuqwleuCqCIsInN1YiI6InVzZXI3NzciLCJlbXBDb2RlIjozNCwiZGVwYXJ0bWVudENvZGUiOjYsImVtcGxveWVlRW1haWwiOiJrYW5nNzc3QGdtYWlsLmNvbSIsImVtcEdyb3VwQ29kZSI6MSwiZW1wbG95ZWVJZCI6InVzZXI3NzciLCJleHAiOjE3MDkwODY0NjIsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVDb2RlIjozNCwiYXV0aG9yaXR5Q29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eU5hbWUiOiJST0xFX1VTRVIifX1dfQ.uqL49wHPUR33A_B4a6HCiiqZw_V209goyNSxWIHnwd8




###메인페이지 근태 퇴근 업데이트
PUT http://localhost:1208/api/v1/mainpage/arrive
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA5MDgxMTc3OTkwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJkZXBhcnRtZW50TmFtZSI6IklU7Jq07JiB7YyAIiwiZW1wbG95ZWVOYW1lIjoi6rCV7ZW066awIiwic3ViIjoidXNlcjA3IiwiZW1wQ29kZSI6MTIsImRlcGFydG1lbnRDb2RlIjo4LCJlbXBsb3llZUVtYWlsIjoia2ltbWluNjk5QGdtYWlsLmNvbTMiLCJlbXBHcm91cENvZGUiOjMsImVtcGxveWVlSWQiOiJ1c2VyMDciLCJleHAiOjE3MDkwODQ3NzcsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVDb2RlIjoxMiwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIn19XX0.JkWhSzzKjt50PO-62WSm-JNgY7sVM7pe2FUlf_Nnmc4




###메인페이지 근태 출퇴근 목록
GET http://localhost:1208/api/v1/mainpage/arrive
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA5MDI0MDQ3MzM1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJkZXBhcnRtZW50TmFtZSI6IklU7Jq07JiB7YyAIiwiZW1wbG95ZWVOYW1lIjoi6rCV7ZW066awIiwic3ViIjoidXNlcjA3IiwiZW1wQ29kZSI6MTIsImRlcGFydG1lbnRDb2RlIjo4LCJlbXBsb3llZUVtYWlsIjoia2ltbWluNjk5QGdtYWlsLmNvbTMiLCJlbXBHcm91cENvZGUiOjMsImVtcGxveWVlSWQiOiJ1c2VyMDciLCJleHAiOjE3MDkwMjc2NDcsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVDb2RlIjoxMiwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIn19XX0.nqFSdXWnm8mlxxwhWH8yDtaQaLfw5UR5NQvkoV6XVgg

