###마이페이지 정보 조회

### 사원번호로 조회
GET http://localhost:1208/api/v1/mypage/emplist?c=12
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA4NDc1NTExNTc4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6Ilxia2ltbWluNjk5QGdtYWlsLmNvbSIsImVtcGxveWVlSWQiOiJ1c2VyMDciLCJleHAiOjE3MDg0NzkxMTEsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVDb2RlIjoxMiwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIn19XX0.C_C01zS_H5f_89tzlw_1wikIDy4cjM9bERg6nfVjRow


### 전화번호, 이메일, 주소 수정하기
PUT http://localhost:1208/api/v1/mypage/modifyinfo/12
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA4NDc1NTExNTc4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6Ilxia2ltbWluNjk5QGdtYWlsLmNvbSIsImVtcGxveWVlSWQiOiJ1c2VyMDciLCJleHAiOjE3MDg0NzkxMTEsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVDb2RlIjoxMiwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIn19XX0.C_C01zS_H5f_89tzlw_1wikIDy4cjM9bERg6nfVjRow

{
  "phone": "010-2222-2223",
  "empEmail": "kanghaerin@gmail.com",
  "address": "만리포 제주도 대구"
}

###비밀 번호 변경하기
PUT http://localhost:1208/api/v1/mypage/modifypwd/12
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4NDg4MDA2NzgxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJlbXBsb3llZUlkIjoidXNlcjA3IiwiZXhwIjoxNzA4NDkxNjA2LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MTIsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiJ9fV19.4UZgee5iC-PXgsxF_xGqTKNpf1tz0jQIZp_vWIaVfoU

{
  "empPwd": "2p8zHMlQwwo",
  "newEmpPwd": "pass07"
}

###프로필사진 마이페이지에서 가져오기
GET http://localhost:1208/api/v1/mypage/find/profile
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4NTAwNDM4NzQ4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJlbXBsb3llZUlkIjoidXNlcjA3IiwiZXhwIjoxNzA4NTA0MDM4LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MTIsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiJ9fV19.KQq3Rwkb99llgE6i1ThVylczneyxO8-gbLSBnq_cyds
Accept: */*


###프로필 사진 변경하기
PUT http://localhost:1208/api/v1/mypage/updateprofile
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzA4NTAwNDM4NzQ4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJlbXBsb3llZUlkIjoidXNlcjA3IiwiZXhwIjoxNzA4NTA0MDM4LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MTIsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiJ9fV19.KQq3Rwkb99llgE6i1ThVylczneyxO8-gbLSBnq_cyds
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="ProfileImage"; filename="desert.png"

< ./desert.png
--WebAppBoundary--