###마이페이지 정보 조회

### 사원번호로 조회
GET http://localhost:1208/api/v1/mypage/emplist?c=12
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3MDY2MjIyNDAzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImthbmdoYWVyaW5AZ21haWwuY29tIiwiZXhwIjoxNzA3MDY5ODIyLCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.uXgIBeEAGRzUEDlEuqLnL0FmQtiSmyu5w4CCIlGVLEs



### 전화번호, 이메일, 주소 수정하기
PUT http://localhost:1208/api/v1/mypage/modifyinfo/12
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3OTc3NjcyMjA3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJlbXBsb3llZUlkIjoidXNlcjA3IiwiZXhwIjoxNzA3OTgxMjcyLCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MTIsImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9VU0VSIn19XX0.Fn0a523m2_XnMM4sTi6QqFRgghGQVznSRJuQ9jrdp_A

{
  "phone": "010-2222-2225",
  "empEmail": "kanghaerin@gmail.com",
  "address": "만리포 제주도 대구"
}

###비밀 번호 변경하기
PUT http://localhost:1208/api/v1/mypage/modifypwd/12
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3ODc5NjE5NjMwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJlbXBsb3llZUlkIjoidXNlcjA3IiwiZXhwIjoxNzA3ODgzMjE5LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlQ29kZSI6MTIsImF1dGhvcml0eUNvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9VU0VSIn19XX0.koj8LOhD6rWwugQkRXIQZxcIlVGWprkjCL9bHyOaJe0

{
  "empPwd": "wJkvJV0Zoic",
  "newEmpPwd": "pass07"
}

###프로필사진 변경하기
POST http://localhost:1208/api/v1/mypage/updateprofile
Content-Type: multipart/form-data
Authorization: Bearer eyJkYXRlIjoxNzA3MTg4ODQwNDI5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJleHAiOjE3MDcxOTI0NDAsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19.30VlsOfsjQvnxIDLanoTyeii-gI3lkVh53YX5zuGO9k
Accept: */*

employeeCode=1234&file=@example.jpg
