###마이페이지 정보 조회

### 사원번호로 조회
GET http://localhost:1208/api/v1/mypage/emplist?c=12
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3MDY2MjIyNDAzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImthbmdoYWVyaW5AZ21haWwuY29tIiwiZXhwIjoxNzA3MDY5ODIyLCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.uXgIBeEAGRzUEDlEuqLnL0FmQtiSmyu5w4CCIlGVLEs



### 전화번호, 이메일, 주소 수정하기
PUT http://localhost:1208/api/v1/mypage/modifyinfo/12
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3MDk5NjQ5MTEwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImthbmdoYWVyaW5AZ21haWwuY29tIiwiZXhwIjoxNzA3MTAzMjQ5LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.CA17CPQGdYKSEUnzl8sSY9cZznlLnDs7BaVErvm5saE

{
  "phone": "010-2222-2225",
  "empEmail": "kanghaerin@gmail.com",
  "address": "만리포 제주도 대구"
}

###비밀 번호 변경하기
PUT http://localhost:1208/api/v1/mypage/modifypwd/12
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3MDk5OTk4MzE1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImthbmdoYWVyaW5AZ21haWwuY29tIiwiZXhwIjoxNzA3MTAzNTk4LCJlbXBsb3llZVJvbGUiOlt7ImVtcGxveWVlTm8iOjAsImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRob3JpdHlDb2RlIjoyLCJhdXRob3JpdHlOYW1lIjoiUk9MRV9BRE1JTiIsImF1dGhvcml0eURlc2MiOiLqtIDrpqzsnpAifX1dfQ.O1IEZ5UDxsKgXK-nxmEpGh3jmlTwuGMof00y_zLHKB0

{
  "empPwd": "pass35",
  "newEmpPwd": "pass36"
}


