### 로그인
POST http://localhost:1208/auth/login
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "employeeId": "wnsrud0001",
  "employeePassword": "wnsrud0001"
}

### 프로젝트 리스트 조회
GET http://localhost:1208/api/v1/project/projects
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3MjA1OTM5MTQwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJleHAiOjE3MDcyMDk1MzksImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19.EUEzO9EdasEVNAZKAqKRUApDP_jpRfrvuIVFtOURN0Q


### 프로젝트 생성
POST http://localhost:1208/api/v1/project/projects
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4MDM5MjM1NTkyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLsnKDsirnsnqwiLCJzdWIiOiJ3bnNydWQwMDAxIiwiZW1wQ29kZSI6MTcsImVtcGxveWVlRW1haWwiOiJjaGVycnlibG9zc29tMUBnbWFpbC5jb20iLCJlbXBsb3llZUlkIjoid25zcnVkMDAwMSIsImV4cCI6MTcwODA0MjgzNSwiZW1wbG95ZWVSb2xlIjpbeyJlbXBsb3llZUNvZGUiOjE3LCJhdXRob3JpdHlDb2RlIjoxLCJhdXRob3JpdHkiOnsiYXV0aG9yaXR5Q29kZSI6MSwiYXV0aG9yaXR5TmFtZSI6IlJPTEVfVVNFUiJ9fV19.aPoeZlkkcGybsWNtHl13UBhv_clgAjKJ5cxqtewbaIo

{
  "projectTitle": "프로젝트 생성 데모 1",
  "projectDescription": "프로젝트 생성 완료.",
  "projectDeadline": "2023-01-03T12:00:00",
  "projectLockedStatus": "Y"
}

### 프로젝트 조회
GET http://localhost:1208/api/v1/project/projects/1
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3MDU0MzU4ODc1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBsb3llZUVtYWlsIjoia2FuZ2hhZXJpbkBnbWFpbC5jb20iLCJleHAiOjE3MDcwNTc5NTgsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19.JBi9CR0_71oCyrPwf9KkTfe3U6IOEoqFaSmJhy29vnk
Authorization: Bearer eyJkYXRlIjoxNzA3MTk4MDE2NTcxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBDb2RlIjoxMiwiZW1wbG95ZWVFbWFpbCI6ImtpbW1pbjY5OUBnbWFpbC5jb20iLCJleHAiOjE3MDcyMDE2MTYsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19.HQtTuUz_Cvwr1kwwDMaXhtVXT3BTIxmvEIOyQZAHecs


### 프로젝트 멤버 초대
POST http://localhost:1208/api/v1/project/projects/1/invite
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3MDU0MzU4ODc1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBsb3llZUVtYWlsIjoia2FuZ2hhZXJpbkBnbWFpbC5jb20iLCJleHAiOjE3MDcwNTc5NTgsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19.JBi9CR0_71oCyrPwf9KkTfe3U6IOEoqFaSmJhy29vnk

[
  1,
  2,
  3
]

###사원 목록 조회
GET http://localhost:1208/api/v1/project/employees
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3MDU0ODMxMDQzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBsb3llZUVtYWlsIjoia2FuZ2hhZXJpbkBnbWFpbC5jb20iLCJleHAiOjE3MDcwNTg0MzEsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19.dBsuUjxvKbAHYOAIYK1_cOcZhqf-mK9n4h1OrLpsT1Q

### 사원 내보내기
DELETE http://localhost:1208/api/v1/project/projects/1/kick/5
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3MDU3MTI2MDUxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJlbXBsb3llZU5hbWUiOiLqsJXtlbTrprAiLCJzdWIiOiJ1c2VyMDciLCJlbXBsb3llZUVtYWlsIjoia2FuZ2hhZXJpbkBnbWFpbC5jb20iLCJleHAiOjE3MDcwNjA3MjYsImVtcGxveWVlUm9sZSI6W3siZW1wbG95ZWVObyI6MCwiYXV0aG9yaXR5Q29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eUNvZGUiOjIsImF1dGhvcml0eU5hbWUiOiJST0xFX0FETUlOIiwiYXV0aG9yaXR5RGVzYyI6Iuq0gOumrOyekCJ9fV19.G28o0odgmDlgRJ7NvoGS-JIi6-3c4CWRKTHiKnzp_TQ